# Generated by Django 5.0.6 on 2024-07-01 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pointage', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='code',
            old_name='ID',
            new_name='id',
        ),
        migrations.AlterField(
            model_name='employe',
            name='familiy_situation',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='partner',
            name='last_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='partner',
            name='name',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
